language: go

go:
  - 1.9

env:
  global:
    # travis encrypt -r subchen/frep GITHUB_TOKEN=5f48......
    - secure: "FZCQBhMnME+CTDQXh3MCcsG6eXd8YtulRj0A/XhSL5hm+BbEDE14VOH1kH04drw/Uynqqdv3lnGae0uigLAqo1jLXJdlD3jfYcjLiQ+0OQVWhqW81xtxE2kNwuWH7ue+bo7czY7JCkB2UXPh5nkWetX0MvEaSGpE4m+xdhBz2Ztiyts8lKUVkZx5VFwjlsaecmF3TvyFZYweIVDtuMv13tNzppQFhuAjCnwET8F2FqIVE+72hsKYKGoxc7OcFNwgGTcoounbC3NzZrtrRmbleRApcPZw+UsFpbRgMvgLwR1LP4ESDe2/LZ6vKZg/NlNspw6c51vn6nDAaVEEnklPtwXqDz96+eTI4gDFguz249p5jXDSJowhsNmLIbI/wnCSaEhIh9Va1qGeai70xiTwBtiPxVx3sud32zjqTtDS7+gcykhIitc8dIqBm4ei1f6/L0duU3tVsHYSChB4Cox6mVGhH9Dsg32KGiFEcgfCVyE9TXU+NRKgmU59JRWDTLKaP9yilvfj/8lB4beyRcoYYPHYNTtOIRnw/7/2pid6UHlR9wxHQCLpc2dcDs7KiJFC6PoBcvuAYPdsFDApQuVHXyz4QYy8yyYGWZL7d4IbVZrOJbOVIT5ldaQFbfMN4ybmS5z2C2W/0Hnepy8CiQZ+zq1zu7tPH41+esRjv36PMQQ="
    # travis encrypt -r subchen/frep DOCKER_PASSWORD=
    - secure: "ItQNYV9fK2Kcr/opj0edOSlPl8aFF4W5Sg6vS65G76Oh9A3T2nGdXYDq4UhUzzGfitmWeOt35sEWt4KD50CNmV3b0yRrro5B044ESSH7aJR7LBFDqm38ijWRsVGhRxNWtJLKwNoWjv/Fh+Ry++O0AowBHYglwgXus/fwK9rjBJOJQua65i3zIJgtgfe/FV/mgSQEqPqb+tmHICZL8Szh4sR6sLjpDfSJO/rbflnXLBssClz+f41aCcOoGYCUfAbQqEnKdtULK9POJEOhlo1usHU3s4LDQI2wNnrF7UrT9STQfED+cnWdEi7DdZNQDE1i0YM3ccSn89M7HWgFnVPu0RBqGKi6ld8KzUAN3dMiJPjvjxhXeoOHqn940pxxq6wWFaVzaccjnkaHpr6lVfRLkIGuvZOIHQjavO2jIlzpfDWf+XHjIdiAre9ttRtgey1f6+vRfTwA+K0/wm0k3MtzBC529faOZ4WnjIhv9XeaQAsox3QOj5TIKY1087mTZF0IW9L+UPUw8bk8thJdnZfpjkN3CmeQ9u5B9iXdEREhpN0z9jp9N3enfXotFffS/v+shrd7bLg0KF/a0dEiASSwcAXZNa2IQiZwKmvwAciAGc6EJdRKLIBuhsDDwXrcLv9C0uMV3GNDPqUvhyBzJlAOtKje1rARW7eFtcUiJheQriA="

sudo: required

services:
  - docker

before_script:
  - go get golang.org/x/tools/cmd/goimports

script:
  - make build

after_success:
  - [ -n "$TRAVIS_TAG" ] && make release

deploy:
  provider: releases
  api_key:
    secure: PlsWtt7ZTXidanmSrrD08TsnCbYg9jdssZk7JKhEhN+pD9ZkT/cEDt047ATP65NIm60xjn9J9sWwPUr70ecBcViMPlDCxuMsd88f0kNtRbWzR45RBqzE8HEAE5mmw2VYzt7dZYXMDgV6I1Rl1ew9GQi0wQkhmIlkOTMlIF1gMztEDs8m2b3kz2eE1GGLzKomvhpwkefgZfeg5APwkLD/3BvOW9yDXeUNA4c+zL/r2+uf+XZFdYs05ebVWqlogswT63LP60rxZhnoNT4Daym/i9SjrS0cmjChMSRT0tsxi+o9sNoEwJmhMmi38I0IBhXv7xqCs/qdd1guyE8qp14kgZEzT42UbB+UG5GSU+HQmiPGcm1GpCmt/QD3y1qb6aIOX+XHsyF0x4DhQxfNmpV+TrbKhTEOhrA6IW4CtEx9WC+B5+K8bu0ermRUsY75lcw8Ah8Ab3C1uF/jbKx2G3KV5mCQ3GXfJRQ94in8dQUL5mKc5UzlC9xqfKBvIvAy7JDTrLAwDjWkxdaGo+v/ldhyYYfblqVNA89YM5998k6Oni0KEP3XvMjVP83ZlYWyfaVELHXnzNOuhxxHAk+YKLaU050t+Kayh7IvISTEBQCgAmsGRqOsbbHuWJ1fglIZR8w9hGs7w4mOcqqz+IoudGBikr5HRG6t388rRXimjEWB6V4=
  file_glob: true
  file: _releases/*
  skip_cleanup: true
  on:
    tags: true
